# Generated by Django 5.1.1 on 2024-10-31 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name=1),
        ),
    ]
